apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: housetransfer
spec:
  createingress: true
  functionref:
    functionweights: null
    name: housetransfer
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /housetransfer/{startyear}/{startmonth}/{endyear}/{endmonth}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /housetransfer/{startyear}/{startmonth}/{endyear}/{endmonth}
