apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: trafficredditharvester
spec:
  createingress: true
  functionref:
    functionweights: null
    name: trafficredditharvester
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /trafficredditharvester
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /trafficredditharvester
