apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: mastodonhotword
spec:
  createingress: true
  functionref:
    functionweights: null
    name: mastodonhotword
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /mastodonhotword/{startdate}/{starttime}/{enddate}/{endtime}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /mastodonhotword/{startdate}/{starttime}/{enddate}/{endtime}
