apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: redinit
spec:
  createingress: true
  functionref:
    functionweights: null
    name: redinit
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /redinit
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /redinit
