apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: victim
spec:
  createingress: true
  functionref:
    functionweights: null
    name: victim
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /victim/{state}/{method}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /victim/{state}/{method}
