apiVersion: fission.io/v1
kind: TimeTrigger
metadata:
  creationTimestamp: null
  name: trafficredditharvester-timer
spec:
  cron: '@every 1h'
  functionref:
    functionweights: null
    name: trafficredditharvester
    type: name
