apiVersion: fission.io/v1
kind: Function
metadata:
  name: youtubeharv
spec:
  environment:
    name: python39
    namespace: default
  package:
    functionName: youtubeharv.main
    packageref:
      name: youtubeharv-pkg
      namespace: default
  InvokeStrategy:
    StrategyType: execution
    ExecutionStrategy:
      ExecutorType: poolmgr
      MinScale: 1
      MaxScale: 2
      Secrets:
        - name: youtube-api-key
          mountPath: /secrets/youtube-api-key
  functionTimeout: 60
  idletimeout: 120
  concurrency: 500
  requestsPerPod: 1
