include:
- ./hello.zip
kind: ArchiveUploadSpec
name: hello-y1zM

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: hello-pkg
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python39
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://hello-y1zM
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-03T05:57:50Z"
