apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  name: youtubelifeapi-route
spec:
  functionref:
    name: youtubelifeapi
    type: name
  methods:
    - GET
  relativeurl: /api/youtubelifeapi/{start}/{end}
