apiVersion: fission.io/v1
kind: Function
metadata:
  name: youtubelifeapi
spec:
  environment:
    name: python39
    namespace: default
  package:
    functionName: youtubelifeapi.main
    packageref:
      name: youtubelifeharv-pkg
      namespace: ""
  InvokeStrategy:
    StrategyType: execution
    ExecutionStrategy:
      ExecutorType: newdeploy
      MinScale: 1
      MaxScale: 2
  functionTimeout: 180
  idletimeout: 180
  concurrency: 500
  requestsPerPod: 1