apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  name: youtubelifeharv-route
spec:
  functionref:
    name: youtubelifeharv
    type: name
  methods:
    - GET
  relativeurl: /api/youtubelifeharv
